name: test

on: [push]

jobs:
  build:
    strategy:
      matrix:
        java-version: [17, 21, 25]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      name: Checkout code

    - name: Set up Java ${{ matrix.java-version }}
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java-version }}

    - name: Build and Test with Java ${{ matrix.java-version }}
      run: ./mvnw -B clean test --file pom.xml